repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.2"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --output-format, concise]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.30
    hooks:
      - id: pip-compile
        name: Compile Prod
        args:
          [pyproject.toml, -o, requirements/prod.txt, --all-extras, --no-header]
        files: pyproject.toml
      - id: pip-compile
        name: Compile Dev
        args: [requirements/dev.in, -o, requirements/dev.txt, --no-header]
        files: ^requirements/.*\.(in|txt)
      - id: pip-compile
        name: Compile Test
        args: [requirements/test.in, -o, requirements/test.txt, --no-header]
        files: ^requirements/.*\.(in|txt)
