version: "3"
services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    expose:
      - 6379
  app:
    build: .
    env_file:
      - docker/prod.env
      - docker/secrets.env
    container_name: app
    restart: always
    command: gunicorn --bind 0.0.0.0:8543 --workers=3 --timeout 120 "cycle_analytics:create_app()"
    ports:
      - 8543:8543
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
