services:
  redis:
    image: redis:7
    container_name: cycleanalytics_cache
    restart: unless-stopped
    expose:
      - 6379
  app:
    build: .
    env_file:
      - docker/prod.env
      - docker/secrets.env
    container_name: cycleanalytics_app
    command: gunicorn --bind 0.0.0.0:8543 "cycle_analytics:create_app()"
    ports:
      - 8543:8543
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
