[tool.poetry]
name = "cycle-analytics"
version = "0.1.0"
description = "WApp for tracking, analyzing, and visualizing bicycle rides and gps tracks"
authors = ["Korbinian Schweiger <korbinian.schweiger@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "cycle_analytics" }]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.2.2"
data-organizer = { git = "https://github.com/kschweiger/data_organizer.git", rev = "1.4.0" }
track-analyzer = { git = "https://github.com/kschweiger/track_analyzer.git", rev = "0.3.2" }
Flask-Caching = "^2.0.1"
gunicorn = "^20.1.0"
dynaconf = "^3.1.11"
flask-wtf = "^1.0.1"
pypika = "^0.48.9"
kaleido = "0.2.1"
pyroutelib3 = "^1.7.2"
pydantic = "^1.10.4"
redis = "^4.5.1"
wtforms = "^3.0.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
mypy = "^0.991"
pre-commit = "^2.21.0"
ipython = "^8.7.0"
ruff = "^0.0.262"


[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-mock = "^3.10.0"
pytest-cov = "^4.0.0"
pytest-sugar = "^0.9.6"

[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "E266", "E402", "PT012"]
# flake8-pytest-style
# PT001:
pytest-fixture-no-parentheses = true
# PT006:
pytest-parametrize-names-type = "tuple"
# PT007:
pytest-parametrize-values-type = "list"
pytest-parametrize-values-row-type = "tuple"
# PT023:
pytest-mark-no-parentheses = true

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
exclude = ["tests/*"]


[tool.ruff]
select = ["E", "F", "I", "PD", "PT", "NPY", "N", "W"]
unfixable = ["F841"]

# [tool.pyright]
# venv = "cycle_analytics"
