[tool.poetry]
name = "cycle-analytics"
version = "0.1.0"
description = "WApp for tracking, analyzing, and visualizing bicycle rides and gps tracks"
authors = ["Korbinian Schweiger <korbinian.schweiger@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "cycle_analytics" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
Flask = "^3.0.0"
Flask-Caching = "^2.1.0"
gunicorn = "^21.2.0"
dynaconf = "^3.2.4"
flask-wtf = "^1.2.1"
kaleido = "0.2.1"
pyroutelib3 = "^1.7.2"
pydantic = "^2.5.3"
redis = "^5.0.1"
wtforms = "^3.1.2"
plotly = "^5.18.0"
sqlalchemy = "^2.0.25"
flask-sqlalchemy = "^3.1.1"
psycopg2 = "^2.9.9"
geo-track-analyzer = "^1.1.2"
flask-debugtoolbar = "^0.14.1"
debugpy = "^1.8.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
mypy = "^1.8.0"
pre-commit = "^3.6.0"
ruff = "^0.1.13"
bpython = "^0.24"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"
pytest-mock = "^3.12.0"
pytest-cov = "^4.1.0"
pytest-sugar = "^0.9.7"
pytest-dependency = "^0.6.0"

[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
select = ["E", "F", "I", "PD", "PT", "NPY", "N", "W", "RET", "ANN", "RUF"]
unfixable = ["F841", "RUF005", "RUF015"]
ignore = ["ANN101", "RUF009", "E731", "RET505", "ANN002", "ANN003", "RUF005"]
ignore-init-module-imports = true
target-version = "py310"

[tool.mypy]
python_version = "3.10"
strict_optional = true
check_untyped_defs = true
exclude = ["tests/*"]

[[tool.mypy.overrides]]
module = "fitparse.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "plotly.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "coloredlogs.*"
ignore_missing_imports = true


# [tool.pyright]
# venv = "cycle_analytics"
