#[default]
ALLOWED_TRACK_EXTENSIONS = ["fit", "gpx"]
SQLALCHEMY_DATABASE_URI = "@format {this.database_type}://{this.database_user}:{this.database_password}@{this.database_server}:{this.database_port}/{this.database_name}"
database_type = "postgresql+psycopg2"
database_schema = "cycle_analytics"
database_user = "dev"
database_port = "5432"
database_name = "development"


[categorized_values]
terrain_types = ["MTB", "Road", "Gravel", "Testing/Setup"]
event_types = [
    "Mechanical",
    "Crash",
    "Service",
    "Repair",
    "Replacement",
    "Purchase",
    "Other",
]
segment_types = ["Single Trail", "Dirt Track", "Gravel track", "Road", "Track"]
difficulties = ["No Difficulty", "Easy", "Moderate", "Difficult", "Break Neck"]
severities = ["Minor", "Medium", "Major", "Critical"]
materials = ["Aluminium", "Carbon", "Titanium"]
type_secification = [
    "Cross-Country",
    "Trail",
    "Enduro",
    "Downhill",
    "Race",
    "Endurance",
]

[defaults]
bike = "Nerve"
ride_type = "MTB"
event_type = "Mechanical"
main_data_table = "main"
raw_track_table = "tracks"
track_table = "tracks_enhanced_v1"
track_overview_table = "tracks_v1_overview"

[db]
name = "CycleAnalytics"
user = "dev"
database = "development"
port = 5432
prefix = "postgresql+psycopg2"
schema = "bike_tracker"

[table_settings]
mandatory_columns = ["ctype"]
optional_columns = ["is_primary", "is_unique", "is_nullable", "default"]
auto_fill_ctypes = ["SERIAL"]
[table_settings.key_types]
ctype = "str"
is_primary = "bool"
is_unique = "bool"
is_nullable = "bool"
default = "any"

[style]
color_sequence = [
    "#20c997",
    "#dc3545",
    "#0d6efd",
    "#ffc107",
    "#d63384",
    "#6f42c1",
]
color_marker = "#198754"
[style.slope_colors]
neutral = "#198754"
min = "#0d6efd"
max = "#dc3545"


[adders]
[adders.ride]
type_choices = ["MTB", "Road", "Gravel", "Testing/Setup"]
[adders.event]
type_choices = [
    "Mechanical",
    "Crash",
    "Service",
    "Repair",
    "Replacement",
    "Purchase",
    "Other",
]
init_map_view_lat = 48.02
init_map_view_long = 10.2
init_map_zoom = 8
[adders.segments]
type_choices = ["Single Trail", "Dirt Track", "Gravel track", "Road", "Track"]

[mappings]
[mappings.severity]
0 = "Minor"
1 = "Medium"
2 = "Major"
3 = "Critical"
[mappings.event_colors]
"Mechanical" = "green"
"Crash" = "red"
[mappings.difficulty]
0 = "No Difficulty"
1 = "Easy"
2 = "Moderate"
3 = "Difficult"
4 = "Break Neck"
[mappings.segment_types]
"default" = "#20c997"
"Single Trail" = "#dc3545"
"Dirt Track" = "#fd7e14"
"Gravel track" = "#ffc107"
"Road" = "#000000"
"Track" = "#0dcaf0"

[overview]
default_types = ["MTB", "Road", "Gravel"]


[landing_page]
[landing_page.events]
n_max_recent = 3
[landing_page.last_ride]
default_type = "MTB"
[landing_page.summary]
default_type = "Any"

[external]
[external.track_enhancer]
name = "OpenTopoElevation"
url = "http://localhost:1409/"
[external.track_enhancer.kwargs]
dataset = "eudem25m"
