tables=["main", "tracks", "events", "goals"]

[defaults]
bike="Nerve"
ride_type="MTB"
event_type="Mechanical"
raw_track_table="tracks"
track_table="tracks_enhanced_v1"

[db]
name="CycleAnalytics"
user="dev"
database="development"
port=5432
prefix="postgresql+psycopg2"
schema="bike_tracker"

[table_settings]
mandatory_columns = ["ctype"]
optional_columns = ["is_primary", "is_unique", "is_nullable", "default"]
auto_fill_ctypes = ["SERIAL"]
[table_settings.key_types]
    ctype="str"
    is_primary="bool"
    is_unique="bool"
    is_nullable="bool"
    default="any"

[style]
color_sequence=["#20c997","#dc3545","#0d6efd","#ffc107","#d63384","#6f42c1"]

[adders]
    [adders.ride]
        type_choices=["MTB","Road","Gravel"]
    [adders.event]
        type_choices=["Mechanical", "Crash", "Service", "Replacement", "Purchase", "Other"]
        init_map_view_lat=48.02
        init_map_view_long=10.2
        init_map_zoom=8

[mappings]
    [mappings.severity]
        0="Minor"
        1="Medium"
        2="Major"
        3="Critical"
    [mappings.event_colors]
        "Mechanical"="green"
        "Crash"="red"

[landing_page]
    [landing_page.events]
        n_max_recent=3
    [landing_page.last_ride]
        default_type="MTB"
    [landing_page.summary]
        default_type="Any"

[main]
    name="main"
    rel_table="tracks"
    rel_table_common_column="id_ride"
    [main.id_ride]
        ctype="SERIAL"
        is_primary=true
    [main.date]
        ctype="DATE"
    [main.start_time]
        ctype="TIME"
        is_nullable=true
        default="NULL"
    [main.ride_time]
        ctype="INTERVAL"
        is_nullable=true
        default="NULL"
    [main.total_time]
        ctype="INTERVAL"
    [main.distance]
        ctype="FLOAT"
    [main.bike]
        ctype="VARCHAR(20)"
        default="Nerve"
    [main.ride_type]
        ctype="VARCHAR(20)"
        is_nullable=true
        default="MTB"


[tracks]
    name="tracks"
    [tracks.id_track]
        ctype="SERIAL"
        is_primary=true
    [tracks.id_ride]
        ctype="INT"
    [tracks.gpx]
        ctype="BYTEA"

[events]
    name="events"
    [events.date]
        ctype="DATE"
        is_primary=true
    [events.event_type]
        ctype="VARCHAR(20)"
    [events.short_description]
        ctype="VARCHAR(20)"
    [events.description]
        ctype="VARCHAR(20)"
        is_nullable=true
    [events.severity]
        ctype="INT"
        is_nullable=true
        default="NULL"
    [events.latitude]
        ctype="FLOAT"
        is_nullable=true
        default="Null"
    [events.longitude]
        ctype="FLOAT"
        is_nullable=true
        default="Null"
    [events.id_ride]
        ctype="INT"
        is_nullable=true
        default="NULL"


[goals]
    name="goals"
    [goals.id_goal]
        ctype="SERIAL"
        is_primary=true
    [goals.year]
        ctype="INT"
    [goals.month]
        ctype="INT"
        is_nullable=true
    [goals.goal_name]
        ctype="VARCHAR(20)"
    [goals.type]
        ctype="VARCHAR(20)"
    [goals.threshold]
        ctype="FLOAT"
    [goals.is_upper_bound]
        ctype="BOOLEAN"
        default=true
    [goals.constraints]
        ctype="JSON"
        is_nullable=true
    [goals.description]
        ctype="TEXT"
        is_nullable=true
    [goals.has_been_reached]
        ctype="BOOLEAN"
        default=false
    [goals.active]
        ctype="BOOLEAN"
        default=true
