[production]
database_schema = "cycle_analytics"

[development]
database_schema = "cycle_analytics"
EXTENSIONS = ["flask_debugtoolbar:DebugToolbarExtension"]
SQLALCHEMY_RECORD_QUERIES = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
DEBUG_TB_PROFILER_ENABLED = true

[default]
cache_type = "SimpleCache"
cache_default_timeout = 300
ALLOWED_TRACK_EXTENSIONS = ["fit", "gpx"]
EXTENSIONS = []
SQLALCHEMY_DATABASE_URI = "@format {this.database_type}://{this.database_user}:{this.database_password}@{this.database_server}:{this.database_port}/{this.database_name}"
database_type = "postgresql+psycopg2"
database_schema = "cycle_analytics"
database_user = "dev"
database_port = "5432"
database_name = "development"


[default.categorized_values]
terrain_types = ["MTB", "Road", "Gravel", "Testing/Setup"]
event_types = [
    "Mechanical",
    "Crash",
    "Service",
    "Repair",
    "Replacement",
    "Purchase",
    "Other",
]
segment_types = ["Single Trail", "Dirt Track", "Gravel track", "Road", "Track"]
difficulties = ["No Difficulty", "Easy", "Moderate", "Difficult", "Break Neck"]
severities = ["Minor", "Medium", "Major", "Critical"]
materials = ["Aluminium", "Carbon", "Titanium"]
type_secification = [
    "Cross-Country",
    "Trail",
    "Enduro",
    "Downhill",
    "Race",
    "Endurance",
]

[default.defaults]
bike = "Nerve"
ride_type = "MTB"
event_type = "Mechanical"
main_data_table = "main"
raw_track_table = "tracks"
track_table = "tracks_enhanced_v1"
track_overview_table = "tracks_v1_overview"


[default.style]
color_sequence = [
    "#20c997",
    "#dc3545",
    "#0d6efd",
    "#ffc107",
    "#d63384",
    "#6f42c1",
]
color_marker = "#198754"
color_border = "#e9ecef"
[default.style.slope_colors]
neutral = "#198754"
min = "#0d6efd"
max = "#dc3545"


[default.adders]
[default.adders.ride]
type_choices = ["MTB", "Road", "Gravel", "Testing/Setup"]
[default.adders.event]
type_choices = [
    "Mechanical",
    "Crash",
    "Service",
    "Repair",
    "Replacement",
    "Purchase",
    "Other",
]
init_map_view_lat = 48.02
init_map_view_long = 10.2
init_map_zoom = 8
[default.adders.segments]
type_choices = ["Single Trail", "Dirt Track", "Gravel track", "Road", "Track"]

[default.mappings]
[default.mappings.severity]
0 = "Minor"
1 = "Medium"
2 = "Major"
3 = "Critical"
[default.mappings.event_colors]
"Mechanical" = "green"
"Crash" = "red"
[default.mappings.difficulty]
0 = "No Difficulty"
1 = "Easy"
2 = "Moderate"
3 = "Difficult"
4 = "Break Neck"
[default.mappings.segment_types]
"default" = "#20c997"
"Single Trail" = "#dc3545"
"Dirt Track" = "#fd7e14"
"Gravel track" = "#ffc107"
"Road" = "#000000"
"Track" = "#0dcaf0"

[default.overview]
default_types = ["MTB", "Road", "Gravel"]


[default.landing_page]
[default.landing_page.events]
n_max_recent = 3
[default.landing_page.last_ride]
default_type = "MTB"
[default.landing_page.summary]
default_type = "Any"

[default.external]
[default.external.track_enhancer]
name = "OpenTopoElevation"
url = "http://localhost:1409/"
[default.external.track_enhancer.kwargs]
dataset = "eudem25m"

[default.matching]
distance = 500

[default.routing]
valid_tags = [
    "primary",
    "trunk",
    "secondary",
    "tertiary",
    "unclassified",
    "cycleway",
    "residential",
    "living_street",
    "track",
    "service",
    "bridleway",
    "footway",
    "steps",
    "path",
]
access = ["access", "vehicle", "bicycle"]
[default.routing.offroad]
name = "Offroad"
[default.routing.offroad.weights]
primary = 0.05
trunk = 0.05
secondary = 0.05
tertiary = 1
unclassified = 1
cycleway = 1
residential = 1.5
living_street = 1
track = 1
service = 1
bridleway = 1.5
footway = 1
steps = 0.5
path = 2
[default.routing.allroad]
name = "All Road"
[default.routing.allroad.weights]
primary = 0.3
trunk = 0.05
secondary = 0.9
tertiary = 1
unclassified = 1
cycleway = 2
residential = 2.5
living_street = 1
track = 1
service = 1
bridleway = 0.8
footway = 0.8
steps = 0.5
path = 1
[default.routing.road]
name = "Road"
[default.routing.road.weights]
primary = 0.3
trunk = 0.1
secondary = 0.9
tertiary = 1
unclassified = 1
cycleway = 2
residential = 2.5
living_street = 1
track = 0.1
service = 1
bridleway = 0.1
footway = 0.8
steps = 0.2
path = 0.01

#############################################################
#   _____                                                   #
#  |  __ \                                                  #
#  | |  | | __ _ _ __   __ _  ___ _ __ _______  _ __   ___  #
#  | |  | |/ _` | '_ \ / _` |/ _ \ '__|_  / _ \| '_ \ / _ \ #
#  | |__| | (_| | | | | (_| |  __/ |   / / (_) | | | |  __/ #
#  |_____/ \__,_|_| |_|\__, |\___|_|  /___\___/|_| |_|\___| #
#                       __/ |                               #
#                      |___/                                #
#                                                           #
#############################################################

[testing]
database_schema = "cycle_analytics_testing"
[testing.matching]
distance = 50
