dynaconf_merge = true
tables = [
    "main",
    "tracks",
    "events",
    "goals",
    "bikes",
    "segments",
    "tracks_enhanced_v1",
    "tracks_v1_overview",
    "ride_notes",
]


[main]
name = "main"
rel_table = "tracks"
rel_table_common_column = "id_ride"
[main.id_ride]
ctype = "SERIAL"
is_primary = true
[main.date]
ctype = "DATE"
[main.start_time]
ctype = "TIME"
is_nullable = true
default = "NULL"
[main.ride_time]
ctype = "INTERVAL"
is_nullable = true
default = "NULL"
[main.total_time]
ctype = "INTERVAL"
[main.distance]
ctype = "FLOAT"
[main.bike]
ctype = "VARCHAR(20)"
default = "Nerve"
[main.ride_type]
ctype = "VARCHAR(20)"
is_nullable = true
default = "MTB"


[tracks]
name = "tracks"
[tracks.id_track]
ctype = "SERIAL"
is_primary = true
[tracks.id_ride]
ctype = "INT"
[tracks.gpx]
ctype = "BYTEA"


[tracks_enhanced_v1]
name = "tracks_enhanced_v1"
[tracks_enhanced_v1.id_track]
ctype = "SERIAL"
is_primary = true
[tracks_enhanced_v1.id_ride]
ctype = "INT"
[tracks_enhanced_v1.gpx]
ctype = "BYTEA"

[tracks_v1_overview]
name = "tracks_v1_overview"
[tracks_v1_overview.id_track]
ctype = "INT"
is_primary = true
is_unique = true
[tracks_v1_overview.moving_time_seconds]
ctype = "FLOAT"
[tracks_v1_overview.total_time_seconds]
ctype = "FLOAT"
[tracks_v1_overview.moving_distance]
ctype = "FLOAT"
[tracks_v1_overview.total_distance]
ctype = "FLOAT"
[tracks_v1_overview.max_velocity]
ctype = "FLOAT"
[tracks_v1_overview.avg_velocity]
ctype = "FLOAT"
[tracks_v1_overview.max_elevation]
ctype = "FLOAT"
is_nullable = true
[tracks_v1_overview.min_elevation]
ctype = "FLOAT"
is_nullable = true
[tracks_v1_overview.uphill_elevation]
ctype = "FLOAT"
is_nullable = true
[tracks_v1_overview.downhill_elevation]
ctype = "FLOAT"
is_nullable = true
[tracks_v1_overview.moving_distance_km]
ctype = "FLOAT"
[tracks_v1_overview.total_distance_km]
ctype = "FLOAT"
[tracks_v1_overview.max_velocity_kmh]
ctype = "FLOAT"
[tracks_v1_overview.avg_velocity_kmh]
ctype = "FLOAT"
[tracks_v1_overview.bounds_min_lat]
ctype = "FLOAT"
[tracks_v1_overview.bounds_max_lat]
ctype = "FLOAT"
[tracks_v1_overview.bounds_min_lng]
ctype = "FLOAT"
[tracks_v1_overview.bounds_max_lng]
ctype = "FLOAT"

[events]
name = "events"
[events.date]
ctype = "DATE"
is_primary = true
[events.event_type]
ctype = "VARCHAR(20)"
[events.short_description]
ctype = "VARCHAR(20)"
[events.description]
ctype = "VARCHAR(20)"
is_nullable = true
[events.severity]
ctype = "INT"
is_nullable = true
default = "NULL"
[events.latitude]
ctype = "FLOAT"
is_nullable = true
default = "Null"
[events.longitude]
ctype = "FLOAT"
is_nullable = true
default = "Null"
[events.id_ride]
ctype = "INT"
is_nullable = true
default = "NULL"
[events.bike]
ctype = "VARCHAR(20)"
is_nullable = true
default = "NULL"

[goals]
name = "goals"
[goals.id_goal]
ctype = "SERIAL"
is_primary = true
[goals.year]
ctype = "INT"
[goals.month]
ctype = "INT"
is_nullable = true
[goals.goal_name]
ctype = "VARCHAR(20)"
[goals.type]
ctype = "VARCHAR(20)"
[goals.threshold]
ctype = "FLOAT"
[goals.is_upper_bound]
ctype = "BOOLEAN"
default = true
[goals.constraints]
ctype = "JSON"
is_nullable = true
[goals.description]
ctype = "TEXT"
is_nullable = true
[goals.has_been_reached]
ctype = "BOOLEAN"
default = false
[goals.active]
ctype = "BOOLEAN"
default = true

[bikes]
name = "bikes"
[bikes.bike_name]
ctype = "VARCHAR(50)"
is_primary = true
[bikes.bike_brand]
ctype = "VARCHAR(50)"
[bikes.bike_model]
ctype = "VARCHAR(50)"
[bikes.bike_frame_material]
ctype = "VARCHAR(50)"
[bikes.bike_type]
ctype = "VARCHAR(50)"
[bikes.bike_type_specification]
ctype = "VARCHAR(50)"
is_nullable = true
default = "NULL"
[bikes.bike_weight]
ctype = "FLOAT"
is_nullable = true
default = "NULL"
[bikes.purchase_date]
ctype = "DATE"
[bikes.decommission_date]
ctype = "DATE"
is_nullable = true
default = "NULL"

[segments]
name = "segments"
[segments.id_segment]
ctype = "SERIAL"
is_primary = true
[segments.segment_name]
ctype = "VARCHAR(50)"
[segments.description]
ctype = "TEXT"
is_nullable = true
[segments.type]
ctype = "VARCHAR(20)"
is_nullable = true
default = "NULL"
[segments.difficulty]
ctype = "INT"
is_nullable = true
default = "NULL"
[segments.distance]
ctype = "FLOAT"
[segments.min_elevation]
ctype = "FLOAT"
is_nullable = true
default = "NULL"
[segments.max_elevation]
ctype = "FLOAT"
is_nullable = true
default = "NULL"
[segments.uphill_elevation]
ctype = "FLOAT"
is_nullable = true
default = "NULL"
[segments.downhill_elevation]
ctype = "FLOAT"
is_nullable = true
default = "NULL"
[segments.bounds_min_lat]
ctype = "FLOAT"
[segments.bounds_max_lat]
ctype = "FLOAT"
[segments.bounds_min_lng]
ctype = "FLOAT"
[segments.bounds_max_lng]
ctype = "FLOAT"
[segments.gpx]
ctype = "BYTEA"
[segments.visited]
ctype = "BOOLEAN"
default = true

[ride_notes]
name = "ride_notes"
[ride_notes.id_ride]
ctype = "INT"
is_primary = true
[ride_notes.note]
ctype = "TEXT"
is_nullable = false
